version: "3.3"
networks:
  internal_network:
    external: true
services:
  servidorloantransfer:
    image: node:lts-alpine
    container_name: "servidorloantransfer"
    stdin_open: true
    restart: always
    expose:
      - "3001"
    ports:
      - "3001:3000"
    environment:
      - "PORT=3000"
    volumes:
      - ./:/development/servidorloantransfer
      - ./uploads:/home/aplicaciones/uploadsloantransfer
    working_dir: /development/servidorloantransfer
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    command: sh -c "npm install && npm install -g pm2 && pm2-runtime ecosystem.config.js --env production"
    #command: sh -c "npm install && npm install -g pm2 && pm2-runtime ecosystem.config.js --watch --env development"
    #command: sh -c "NODE_ENV=development npm run dev"
    links:
      - mongodbloantransfer
      - redisloantransfer
    networks:
      - internal_network
    depends_on:
      - mongodbloantransfer
      - redisloantransfer
  mongodbloantransfer:
    image: mongo:4.4
    container_name: "mongodbloantransfer"
    restart: always
    volumes:
      #- ./data/db:/home/aplicaciones/databases/mongodbData/mongodbSubastas
      - ./data/db:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
  #    MONGO_INITDB_DATABASE: "subastas_loantransfer"
  #    #MONGO_INITDB_ROOT_USERNAME: user
  #    #MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 3400:27017
    networks:
      - internal_network
    #command: mongod --logpath=/dev/null --auth # --quiet
    command: "--logpath=/dev/null"
  redisloantransfer:
    container_name: "redisloantransfer"
    restart: always
    image: "redis:6.2.5"
    volumes:
      - ./redis-data:/home/aplicaciones/databases/redisData/redisloantransfer
      - ./redis.conf:/home/aplicaciones/conf/redis.conf
    ports:
      - "6380:6379"
    networks:
      - internal_network