version: "3.3"
networks:
  internal_network:
    external: true
services:
  servidorloantransfer:
    image: node:lts-alpine
    container_name: "servidorloantransfer"
    stdin_open: true
    restart: always
    expose:
      - "3001"
    ports:
      - "3001:3000"
    environment:
      - "PORT=3000"
    volumes:
      - ./:/development/servidorloantransfer
      - ./uploads:/home/aplicaciones/uploadsloantransfer
      - /etc/letsencrypt/:/development/servidorloantransfer/certs
    working_dir: /development/servidorloantransfer
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    command: sh -c "npm install && npm install -g pm2 && pm2-runtime ecosystem.config.js --env production"
    #command: sh -c "npm install && npm install -g pm2 && pm2-runtime ecosystem.config.js --watch --env development"
    #command: sh -c "NODE_ENV=development npm run dev"
    networks:
      - internal_network