version: "3.3"
networks:
  internal_network:
    external: true
services:
  servidornplbroker:
    image: node:lts-alpine
    container_name: "servidornplbroker"
    stdin_open: true
    restart: always
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - "PORT=3000"
    volumes:
      - ./:/development/servidornplbroker
      - ./uploads:/home/aplicaciones/uploadsnplbroker
    working_dir: /development/servidornplbroker
    command: sh -c "npm install && npm install -g pm2 && pm2-runtime ecosystem.config.js --env production"
    #command: sh -c "npm install && npm install -g pm2 && pm2-runtime ecosystem.config.js --watch --env development"
    #command: sh -c "NODE_ENV=development npm run dev"
    links:
      - redisloantransfer
    networks:
      - internal_network
    depends_on:
      - redisloantransfer
  redisloantransfer:
    container_name: "redisloantransfer"
    restart: always
    image: "redis:6.2.5"
    volumes:
      - ./redis-data:/home/aplicaciones/databases/redisData/redisloantransfer
      - ./redis.conf:/home/aplicaciones/conf/redis.conf
    ports:
      - "6380:6379"
    networks:
      - internal_network