version: "3.3"
services:
  servidorloantransfer:
    image: node:lts-alpine
    stdin_open: true
    restart: always
    expose:
      - "3001"
    ports:
      - "3001:3000"
    environment:
      - "PORT=3000"
    volumes:
      - ./:/development/servidorloantransfer
      - ./uploads:/home/aplicaciones/uploadsloantransfer
    working_dir: /development/servidorloantransfer
    command: sh -c "npm install && npm install -g pm2 && pm2-runtime app.js --watch"
    #command: sh -c "npm start app.js"
    links:
      - mongodbloantransfer
      - redisloantransfer
    depends_on:
      - mongodbloantransfer
      - redisloantransfer
  mongodbloantransfer:
    image: mongo:4.4
    container_name: "mongodbloantransfer"
    restart: always
    volumes:
      - ./data/db:/home/aplicaciones/databases/mongodbData/mongodbSubastas
    environment:
      MONGO_INITDB_DATABASE: "subastas_loantransfer"
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 3400:27017
    command: mongod --logpath=/dev/null --auth # --quiet
  redisloantransfer:
    container_name: "redisloantransfer"
    restart: always
    image: "redis:6.2.5"
    volumes:
      - ./redis-data:/home/aplicaciones/databases/redisData/redisloantransfer
      - ./redis.conf:/home/aplicaciones/conf/redis.conf
    ports:
      - "6380:6379"
