version: "3.3"
services:
  servidorSubastas:
    image: node:lts-alpine
    stdin_open: true
    restart: always
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - "PORT=3000"
    volumes:
      - ./:/development/servidorSubastas
      - ./uploads:/home/aplicaciones/uploads
    working_dir: /development/servidorSubastas
    command: sh -c "npm install && npm start"
    links:
      - mongodbSubastas
      - redisSubastas
    depends_on:
      - mongodbSubastas
      - redisSubastas
  mongodbSubastas:
    image: mongo:4.4
    container_name: "mongodbSubastas"
    restart: always
    volumes:
      - ./data/db:/home/aplicaciones/databases/mongodbData/mongodbSubastas
    environment:
      MONGO_INITDB_DATABASE: "subastas_db"
      #MONGO_INITDB_ROOT_USERNAME: user
      #MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 3500:27017
    command: mongod --logpath=/dev/null --auth # --quiet
  redisSubastas:
    container_name: "redisSubastas"
    image: "redis:6.2.5"
    volumes:
      - ./redis-data:/home/aplicaciones/databases/redisData/redisSubastas
      - ./redis.conf:/home/aplicaciones/conf/redis.conf
    ports:
      - "6379:6379"
