version: "3.3"
services:
  servidorSubastas:
    image: node:lts-alpine
    stdin_open: true
    restart: always
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - "PORT=3000"
    volumes:
      - ./:/development/servidorSubastas
      - ./uploads:/home/aplicaciones/uploads/
    working_dir: /development/servidorSubastas
    command: sh -c "npm install && npm start"
    links:
      - mongodb
      - redis
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo:4.4
    container_name: "mongodb"
    restart: always
    volumes:
      - ./data/db:/home/aplicaciones/databases/mongodbData/mongodb
    environment:
      MONGO_INITDB_DATABASE: "subastasDB"
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet
  redis:
    container_name: "redis"
    image: "redis:6.2-alpine"
    volumes:
      - ./redis-data:/home/aplicaciones/databases/redisData/redis
    ports:
      - "6379:6379"
