version: "3.3"
services:
  servidorSubastas2:
    image: node:lts-alpine
    stdin_open: true
    restart: always
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - "PORT=3000"
    volumes:
      - ./:/development/servidorSubastas2
      - ./uploads:/home/aplicaciones/uploads2
    working_dir: /development/servidorSubastas2
    command: sh -c "npm install && npm install -g pm2 && pm2-runtime app.js --watch"
    #command: sh -c "npm start app.js"
    links:
      - mongodbSubastas2
      - redisSubastas2
    depends_on:
      - mongodbSubastas2
      - redisSubastas2
  mongodbSubastas2:
    image: mongo:4.4
    container_name: "mongodbSubastas2"
    restart: always
    volumes:
      - ./data/db:/home/aplicaciones/databases/mongodbData/mongodbSubastas
    environment:
      MONGO_INITDB_DATABASE: "subastas_db2"
      #MONGO_INITDB_ROOT_USERNAME: user
      #MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 3400:27017
    command: mongod --logpath=/dev/null --auth # --quiet
  redisSubastas2:
    container_name: "redisSubastas2"
    restart: always
    image: "redis:6.2.5"
    volumes:
      - ./redis-data:/home/aplicaciones/databases/redisData/redisSubastas2
      - ./redis.conf:/home/aplicaciones/conf/redis.conf
    ports:
      - "6379:6379"
