GET http://localhost:3006
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTY0MTAxMTEsImV4cCI6MTYxNjQxMzcxMSwiYXVkIjoiNjA1ODZlNTRlOTA0Mjk0OWE4MGI1MDJhIiwiaXNzIjoiZ2l0LmNvbSJ9.gISXVR8B9sCeEQOzsKf58fM_QdK742wOSrHaI9EA8IU

###Login Route
POST http://localhost:3006/auth/login
Content-Type: application/json

{
  "email": "nobodyuser@gmail.com",
  "password": "1234"
}


###Register Route
POST http://localhost:3006/auth/register
Content-Type: application/json

{
  "email": "nobodyuser@gmail.com",
  "password": "1234"
}

###Refresh token Route
POST http://localhost:3006/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTY0MDgxNDgsImV4cCI6MTY0Nzk2NTc0OCwiYXVkIjoiNjA1ODZlNTRlOTA0Mjk0OWE4MGI1MDJhIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.GI2SpDI6JmkwtM6zm4A2Nz42zrxW8-zlmXNuD8mXdhg"
}

###Logout Route
DELETE http://localhost:3006/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTY0MDgxNDgsImV4cCI6MTY0Nzk2NTc0OCwiYXVkIjoiNjA1ODZlNTRlOTA0Mjk0OWE4MGI1MDJhIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.GI2SpDI6JmkwtM6zm4A2Nz42zrxW8-zlmXNuD8mXdhg"
}